import { For } from "solid-js";
import MountainArt from "../components/MountainArt";
import SectionHeading from "../components/SectionHeading";
import ContentCard from "../components/ContentCard";
import { activities, articles, clients, episodes, projects, showcase } from "../data/content";
import styles from "./HomePage.module.css";

export default function HomePage() {
  document.title = "South Mountain Technologies — Build locally. Share openly.";
  return <>
    <section class={`container ${styles.hero}`}><div class={styles.heroCopy}><span class="eyebrow">South Mountain, Pennsylvania</span><h1>Build locally.<br />Share openly.<br /><em>Geek out together.</em></h1><p class="lede">South Mountain Technologies is a developer community for people who want to build software, share knowledge, explore new tools, and find other builders close to home.</p><div class={styles.heroActions}><a class="button" data-variant="primary" href="/join">Join the Community</a><a class="button" href="/projects">Explore Projects</a></div><a class={styles.workLink} href="/client-work">Have something to build? Work with us →</a></div><div class={styles.heroVisual}><MountainArt /><aside class={styles.statusPanel} aria-label="Community status"><div><span>Community</span><strong>Forming now</strong><i /></div><div><span>Monthly podcast</span><strong>In development</strong><i data-warm /></div><div><span>Local meetup</span><strong>Planning phase</strong><i /></div><div><span>GitHub projects</span><strong>Open to contributors</strong><i /></div></aside></div></section>
    <section class={`container ${styles.activity}`} aria-label="Community activity"><div class={styles.activityHeading}><span>△ From the community</span><a href="/community">View community →</a></div><div class={styles.activityGrid}><For each={activities}>{(item,index) => <div><span>{String(index()+1).padStart(2,"0")}</span><p>{item}</p></div>}</For></div></section>
    <section class={`container ${styles.splitSection}`}><div><SectionHeading eyebrow="Featured podcast" title="From the Mountain" action={{label:"Podcast",href:"/podcast"}} /><ContentCard item={episodes[0]} featured /></div><div><SectionHeading eyebrow="Latest articles" title="What We’re Talking About" action={{label:"All articles",href:"/articles"}} /><div class={styles.articleGrid}><For each={articles.slice(0,4)}>{item => <ContentCard item={item} />}</For></div></div></section>
    <section class={`container ${styles.section}`}><SectionHeading eyebrow="Built on the Mountain" title="Community Projects" copy="Open experiments, useful tools, questionable ideas, and projects we build because they sound fun." action={{label:"All projects",href:"/projects"}} /><div class={styles.projectsGrid}><ContentCard item={projects[0]} featured /><div class={styles.stack}><For each={projects.slice(1)}>{item => <ContentCard item={item} />}</For></div></div></section>
    <section class={`container ${styles.section}`}><SectionHeading eyebrow="What are you building?" title="Developer Showcase" copy="Weekend experiments, production apps, learning projects, hardware, games, libraries — if you built it, bring it." action={{label:"Submit yours",href:"/showcase"}} /><div class={styles.showcaseGrid}><For each={showcase}>{item => <article class={styles.showcaseCard}><div class={styles.preview}><span>&gt;_</span><strong>{item.title}</strong></div><div class={styles.showcaseMeta}><span>{item.maker}</span><em>{item.state}</em></div><h3>{item.title}</h3><p>{item.summary}</p><div><For each={item.tags}>{tag => <span class="tag">{tag}</span>}</For></div></article>}</For></div></section>
    <section class={`container ${styles.section}`}><SectionHeading eyebrow="The Break Room" title="Memes, Weird Links & Dev Polls" copy="Because building software is serious business. Mostly." /><div class={styles.breakGrid}><article class={styles.meme}><small>Meme of the week</small><div><strong>works on<br />my machine</strong><span>¯\\_(ツ)_/¯</span></div><p>— every developer, eventually</p></article><article class={styles.weird}><small>Strange but true</small><h3>Repos we would absolutely click</h3><ul><li>is-it-a-bug-or-a-feature</li><li>dependency-roulette</li><li>css-i-hardly-know-her</li></ul><a href="/community">Bring your weird link →</a></article><article class={styles.poll}><small>Developer poll</small><h3>Which problem are you currently pretending does not exist?</h3><div><span>Dependency updates</span><i style={{width:"72%"}} /></div><div><span>Test coverage</span><i style={{width:"54%"}} /></div><div><span>The deploy pipeline</span><i style={{width:"41%"}} /></div><a href="/community">Vote when community voting opens →</a></article></div></section>
    <section class={styles.eventsBand}><div class={`container ${styles.eventsGrid}`}><div><span class="eyebrow">Meet at the Trailhead</span><h2>Events, meetups, and chances to connect.</h2><p>We’re working toward a monthly South Mountain developer meetup. Help choose the venue, format, topics, and first date.</p><a class="button" href="/events">Help plan the first meetup</a></div><a class={styles.eventCard} href="/events/south-mountain-developer-meetup"><small>In planning</small><h3>South Mountain Developer Meetup</h3><p>Two short talks. Project show-and-tell. Open discussion. Food. Actual conversations.</p><span>Details coming soon →</span></a></div></section>
    <section class={`container ${styles.section}`}><SectionHeading eyebrow="Everyone starts somewhere" title="Our Community Values" /><div class={styles.values}><div><b>01</b><h3>Curiosity over credentials</h3><p>You do not need a CS degree or a senior title to participate.</p></div><div><b>02</b><h3>Build in public</h3><p>Share unfinished work, decisions, wins, and wrong turns.</p></div><div><b>03</b><h3>Teach what you know</h3><p>A five-minute explanation can unlock something for someone else.</p></div><div><b>04</b><h3>Leave the trail better</h3><p>Document what you learn and make space for the next contributor.</p></div></div></section>
    <section class={`container ${styles.clientSection}`}><div><span class="eyebrow">Community first. Client work too.</span><h2>We build useful things.</h2><p>Selected commercial work gives us a place to exercise the same practical engineering skills we explore in the community.</p><a class="button" href="/client-work">Start a conversation</a></div><div class={styles.clientCards}><For each={clients}>{item => <ContentCard item={item} />}</For></div></section>
    <section class={`container ${styles.cta}`}><div><span class="eyebrow">Join us at the trailhead</span><h2>Bring the project you can’t stop talking about.</h2><p>Get meetup updates, podcast news, project calls, and the best links shared by the community.</p></div><div class={styles.ctaActions}><a class="button" data-variant="primary" href="/join">Join the Community</a><a class="button" href="mailto:chris@southmountaintech.com">Email Chris</a></div></section>
  </>;
}
