import { A, useLocation } from "@solidjs/router";
import { For, Show, createSignal, onMount, type ParentProps } from "solid-js";
import BrandMark from "./BrandMark";
import SearchDialog from "./SearchDialog";
import { navItems } from "../data/content";
import styles from "./AppShell.module.css";

export default function AppShell(props: ParentProps) {
  const location = useLocation();
  const [menuOpen, setMenuOpen] = createSignal(false);
  const [theme, setTheme] = createSignal<"dark" | "light">("dark");
  onMount(() => { const stored = localStorage.getItem("smt-theme"); const initial = stored === "light" ? "light" : "dark"; setTheme(initial); document.documentElement.dataset.theme = initial; });
  const toggleTheme = () => { const next = theme() === "dark" ? "light" : "dark"; setTheme(next); document.documentElement.dataset.theme = next; localStorage.setItem("smt-theme", next); };
  const isActive = (href: string) => location.pathname === href || (href !== "/" && location.pathname.startsWith(`${href}/`));
  return <div class={styles.shell}><div class={styles.announcement}><div class="container"><span>▲</span> We’re in launch mode — building the clubhouse for developers around South Mountain, PA. <A href="/join">Help shape it →</A></div></div><header class={styles.header}><div class={`container ${styles.headerInner}`}><BrandMark /><nav class={styles.desktopNav} aria-label="Main navigation"><A href="/" classList={{ [styles.active]: location.pathname === "/" }}>Home</A><For each={navItems}>{([label,href]) => <A href={href} classList={{ [styles.active]: isActive(href) }}>{label}</A>}</For></nav><div class={styles.actions}><SearchDialog /><button class={styles.iconButton} type="button" onClick={toggleTheme} aria-label={`Switch to ${theme() === "dark" ? "light" : "dark"} theme`}><span aria-hidden="true">{theme() === "dark" ? "☼" : "☾"}</span></button><a class={styles.iconButton} href="https://github.com/chrisbirster/smtntech" target="_blank" rel="noreferrer" aria-label="GitHub repository">GH</a><A class="button" data-variant="primary" href="/join">Join</A><button class={styles.menuButton} type="button" onClick={() => setMenuOpen(v => !v)} aria-expanded={menuOpen()} aria-controls="mobile-menu">Menu</button></div></div><Show when={menuOpen()}><nav id="mobile-menu" class={styles.mobileNav} aria-label="Mobile navigation"><A href="/" onClick={() => setMenuOpen(false)}>Home</A><For each={navItems}>{([label,href]) => <A href={href} onClick={() => setMenuOpen(false)}>{label}</A>}</For><A href="/notes" onClick={() => setMenuOpen(false)}>Meeting Notes</A><A href="/join" onClick={() => setMenuOpen(false)}>Join the Community</A></nav></Show></header><main id="main-content" class={styles.main}>{props.children}</main><footer class={styles.footer}><div class={`container ${styles.footerGrid}`}><div class={styles.footerBrand}><BrandMark /><p>Building software. Sharing knowledge. Strengthening our local tech community.</p><span>⌖ South Mountain, Pennsylvania</span></div><div><h3>Explore</h3><A href="/podcast">Podcast</A><A href="/articles">Articles</A><A href="/projects">Projects</A><A href="/events">Events</A></div><div><h3>Community</h3><A href="/community">Community</A><A href="/join">Join</A><A href="/notes">Meeting Notes</A><A href="/showcase">Showcase</A></div><div><h3>Organization</h3><A href="/about">About</A><A href="/client-work">Client Work</A><a href="mailto:chris@southmountaintech.com">Email</a><a href="https://github.com/chrisbirster/smtntech">GitHub</a></div></div><div class={`container ${styles.footerBottom}`}><span>© 2026 South Mountain Technologies</span><span>Built near South Mountain, PA ♡</span></div></footer></div>;
}
